apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: marypearl/productcatalogservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: default
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
